SET NAMES UTF8;
SET AUTODDL OFF;

DELETE FROM Sector_Economico;
DELETE FROM Nivel_Socioeconomico;
DELETE FROM Tipo_Vivienda;
DELETE FROM Institucion_Educativa;
DELETE FROM Nivel_Educativo;
DELETE FROM Grupo_Etario;
DELETE FROM Discapacidad;
DELETE FROM Religion;
DELETE FROM Estado_Civil;
DELETE FROM Idioma;
DELETE FROM Etnia;
DELETE FROM Sexo;
COMMIT;
INSERT INTO Sexo(id_sexo, nombre_sexo) VALUES (1, 'Femenino');
INSERT INTO Sexo(id_sexo, nombre_sexo) VALUES (2, 'Masculino');
INSERT INTO Sexo(id_sexo, nombre_sexo) VALUES (3, 'Otro');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (1, 'Maya K''iche''', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (2, 'Maya Q''eqchi''', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (3, 'Maya Kaqchikel', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (4, 'Maya Mam', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (5, 'Maya Q''anjob''al', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (6, 'Maya Poqomchi''', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (7, 'Maya Achi''', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (8, 'Maya Ixil', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (9, 'Maya Tz''utujil', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (10, 'Maya Chuj', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (11, 'Maya Jakalteko', 'Maya');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (12, 'Garífuna', 'Afro');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (13, 'Xinca', 'Indigena');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (14, 'Ladino', 'Mestizo');
INSERT INTO Etnia(id_etnia, nombre_etnia, descripcion) VALUES (15, 'Otro', 'Otro');
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (1, 'Español', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (2, 'K''iche''', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (3, 'Q''eqchi''', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (4, 'Kaqchikel', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (5, 'Mam', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (6, 'Q''anjob''al', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (7, 'Poqomchi''', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (8, 'Achi''', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (9, 'Ixil', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (10, 'Tz''utujil', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (11, 'Chuj', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (12, 'Jakalteko', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (13, 'Garífuna', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (14, 'Xinca', 1);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (15, 'Inglés', 0);
INSERT INTO Idioma(id_idioma, nombre_idioma, es_oficial) VALUES (16, 'Francés', 0);
INSERT INTO Estado_Civil(id_estado_civil, nombre_estado_civil) VALUES (1, 'Soltero/a');
INSERT INTO Estado_Civil(id_estado_civil, nombre_estado_civil) VALUES (2, 'Casado/a');
INSERT INTO Estado_Civil(id_estado_civil, nombre_estado_civil) VALUES (3, 'Unido/a');
INSERT INTO Estado_Civil(id_estado_civil, nombre_estado_civil) VALUES (4, 'Divorciado/a');
INSERT INTO Estado_Civil(id_estado_civil, nombre_estado_civil) VALUES (5, 'Viudo/a');
INSERT INTO Estado_Civil(id_estado_civil, nombre_estado_civil) VALUES (6, 'Separado/a');
INSERT INTO Religion(id_religion, nombre_religion) VALUES (1, 'Católica');
INSERT INTO Religion(id_religion, nombre_religion) VALUES (2, 'Evangélica');
INSERT INTO Religion(id_religion, nombre_religion) VALUES (3, 'Mormona');
INSERT INTO Religion(id_religion, nombre_religion) VALUES (4, 'Testigo de Jehová');
INSERT INTO Religion(id_religion, nombre_religion) VALUES (5, 'Maya');
INSERT INTO Religion(id_religion, nombre_religion) VALUES (6, 'Sin religión');
INSERT INTO Religion(id_religion, nombre_religion) VALUES (7, 'Otra');
INSERT INTO Discapacidad(id_discapacidad, nombre_discapacidad, descripcion) VALUES (1, 'Visual', 'Vista');
INSERT INTO Discapacidad(id_discapacidad, nombre_discapacidad, descripcion) VALUES (2, 'Auditiva', 'Oído');
INSERT INTO Discapacidad(id_discapacidad, nombre_discapacidad, descripcion) VALUES (3, 'Motora', 'Movilidad');
INSERT INTO Discapacidad(id_discapacidad, nombre_discapacidad, descripcion) VALUES (4, 'Intelectual', 'Cognitiva');
INSERT INTO Discapacidad(id_discapacidad, nombre_discapacidad, descripcion) VALUES (5, 'Mental', 'Psicosocial');
INSERT INTO Discapacidad(id_discapacidad, nombre_discapacidad, descripcion) VALUES (6, 'Múltiple', 'Varios');
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (1, '0-4', 0, 4);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (2, '5-9', 5, 9);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (3, '10-14', 10, 14);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (4, '15-19', 15, 19);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (5, '20-29', 20, 29);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (6, '30-39', 30, 39);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (7, '40-49', 40, 49);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (8, '50-59', 50, 59);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (9, '60-69', 60, 69);
INSERT INTO Grupo_Etario(id_grupo_etario, nombre_grupo_etario, rango_edad_min, rango_edad_max) VALUES (10, '70+', 70, 120);
INSERT INTO Nivel_Educativo(id_nivel_educativo, nombre_nivel, orden, descripcion) VALUES (1, 'Ninguno', 1, 'Sin estudios');
INSERT INTO Nivel_Educativo(id_nivel_educativo, nombre_nivel, orden, descripcion) VALUES (2, 'Preprimaria', 2, 'Inicial');
INSERT INTO Nivel_Educativo(id_nivel_educativo, nombre_nivel, orden, descripcion) VALUES (3, 'Primaria', 3, '1-6');
INSERT INTO Nivel_Educativo(id_nivel_educativo, nombre_nivel, orden, descripcion) VALUES (4, 'Básico', 4, 'Secundaria');
INSERT INTO Nivel_Educativo(id_nivel_educativo, nombre_nivel, orden, descripcion) VALUES (5, 'Diversificado', 5, 'Media');
INSERT INTO Nivel_Educativo(id_nivel_educativo, nombre_nivel, orden, descripcion) VALUES (6, 'Universitario', 6, 'Superior');
INSERT INTO Nivel_Educativo(id_nivel_educativo, nombre_nivel, orden, descripcion) VALUES (7, 'Postgrado', 7, 'Maestría');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (1, 120, 'Escuela 1', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (2, 170, 'Escuela 2', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (3, 74, 'Escuela 3', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (4, 288, 'Escuela 4', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (5, 64, 'Escuela 5', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (6, 138, 'Escuela 6', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (7, 151, 'Escuela 7', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (8, 295, 'Escuela 8', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (9, 235, 'Escuela 9', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (10, 325, 'Escuela 10', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (11, 206, 'Escuela 11', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (12, 205, 'Escuela 12', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (13, 12, 'Escuela 13', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (14, 282, 'Escuela 14', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (15, 169, 'Escuela 15', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (16, 210, 'Escuela 16', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (17, 173, 'Escuela 17', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (18, 49, 'Escuela 18', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (19, 254, 'Escuela 19', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (20, 325, 'Escuela 20', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (21, 280, 'Escuela 21', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (22, 265, 'Escuela 22', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (23, 108, 'Escuela 23', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (24, 218, 'Escuela 24', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (25, 181, 'Escuela 25', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (26, 332, 'Escuela 26', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (27, 170, 'Escuela 27', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (28, 31, 'Escuela 28', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (29, 205, 'Escuela 29', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (30, 89, 'Escuela 30', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (31, 6, 'Escuela 31', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (32, 137, 'Escuela 32', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (33, 287, 'Escuela 33', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (34, 130, 'Escuela 34', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (35, 67, 'Escuela 35', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (36, 172, 'Escuela 36', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (37, 297, 'Escuela 37', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (38, 330, 'Escuela 38', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (39, 314, 'Escuela 39', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (40, 213, 'Escuela 40', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (41, 244, 'Escuela 41', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (42, 248, 'Escuela 42', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (43, 174, 'Escuela 43', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (44, 7, 'Escuela 44', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (45, 20, 'Escuela 45', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (46, 113, 'Escuela 46', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (47, 326, 'Escuela 47', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (48, 62, 'Escuela 48', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (49, 339, 'Escuela 49', 'Público');
INSERT INTO Institucion_Educativa(id_institucion_edu, id_municipio, nombre_institucion, sector) VALUES (50, 138, 'Escuela 50', 'Público');
INSERT INTO Tipo_Vivienda(id_tipo_vivienda, nombre_tipo_vivienda) VALUES (1, 'Propia');
INSERT INTO Tipo_Vivienda(id_tipo_vivienda, nombre_tipo_vivienda) VALUES (2, 'Alquilada');
INSERT INTO Tipo_Vivienda(id_tipo_vivienda, nombre_tipo_vivienda) VALUES (3, 'Prestada');
INSERT INTO Tipo_Vivienda(id_tipo_vivienda, nombre_tipo_vivienda) VALUES (4, 'Cedida');
INSERT INTO Tipo_Vivienda(id_tipo_vivienda, nombre_tipo_vivienda) VALUES (5, 'Invasión');
INSERT INTO Tipo_Vivienda(id_tipo_vivienda, nombre_tipo_vivienda) VALUES (6, 'Otra');
INSERT INTO Nivel_Socioeconomico(id_nivel_socio, nombre_nivel, ingreso_min, ingreso_max) VALUES (1, 'Extremo', 0, 2000);
INSERT INTO Nivel_Socioeconomico(id_nivel_socio, nombre_nivel, ingreso_min, ingreso_max) VALUES (2, 'Bajo', 2000, 4500);
INSERT INTO Nivel_Socioeconomico(id_nivel_socio, nombre_nivel, ingreso_min, ingreso_max) VALUES (3, 'Medio Bajo', 4500, 8000);
INSERT INTO Nivel_Socioeconomico(id_nivel_socio, nombre_nivel, ingreso_min, ingreso_max) VALUES (4, 'Medio', 8000, 15000);
INSERT INTO Nivel_Socioeconomico(id_nivel_socio, nombre_nivel, ingreso_min, ingreso_max) VALUES (5, 'Medio Alto', 15000, 30000);
INSERT INTO Nivel_Socioeconomico(id_nivel_socio, nombre_nivel, ingreso_min, ingreso_max) VALUES (6, 'Alto', 30000, 999999);
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (1, 'Agro', 'A');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (2, 'Manufactura', 'C');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (3, 'Construcción', 'F');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (4, 'Comercio', 'G');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (5, 'Transporte', 'H');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (6, 'Turismo', 'I');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (7, 'TIC', 'J');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (8, 'Finanzas', 'K');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (9, 'Servicios', 'M');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (10, 'Educación', 'P');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (11, 'Salud', 'Q');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (12, 'Gobierno', 'O');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (13, 'Doméstico', 'T');
INSERT INTO Sector_Economico(id_sector_econ, nombre_sector, codigo_ciiu) VALUES (14, 'Otros', 'S');
COMMIT;